### ISSUE TITLE
dbo_classes.txt and classes_lookup.json ?

### ISSUE THREAD

**Issue by maya-25** [Fcabla/DBpedia-abstracts-to-RDF#1]
I would like to ask these files consist of general DBpedia classes (Ontology) that can be used for any dataset or Are they related to your specific dataset?
Thanks!

**Comment by Fcabla** [comment]
These classes have been extracted from the 2016-10 version of the DBpedia ontology. I think they are all the classes in this version. The first file is a list with all classes, whereas the second file is a dictionary that associates the name of a class (rdfs:label) with the URI that corresponds to it.

**Comment by maya-25** [comment]
1.) I am a little confused, Are these ontologies requirement-specific or general. I see the list of  [ontologies](https://archivo.dbpedia.org/list) But how do I decide which ontology I should use. Like my dataset related to fake news detection. Should I use the same ontology .owl file which you are using or different? Also, are the common verb or prep files are of course related to your dataset abstract?

2.) In `build_lookup_table.py`, the DBpedia ontology file is not used in the code then how you are replacing prepositions by ontology property? I am getting all UNK like:
`"publish": {
        "in": "UNK",
        "on": "UNK",
        "at": "UNK",
        "as": "UNK",
        "for": "UNK",
        "from": "UNK",
        "to": "UNK",
        "with": "UNK",
        "during": "UNK",
        "after": "UNK",
        "of": "UNK",
        "into": "UNK",
        "DEF": "UNK"`

**Comment by maya-25** [comment]
If you get some time, could you please answer the above points?
Thanks!

**Comment by Fcabla** [comment]
Sorry for the delayed answer, 
Regarding (1), in my case I used the DBpedia ontology since the objective of the work is to translate raw text to RDF format using DBpedia classes and properties (since this work is a GSoC project with DBpedia). The most common prepositions and verbs have been extracted from the dataset used (long abstracts DBpedia 2016-10) by using the script [most_common_verbs.py](https://github.com/Fcabla/DBpedia-abstracts-to-RDF/blob/main/code/scripts/most_common_verbs.py) and [most_common_verbs.py](cumsum_common_verbs_preps.py).

Regarding (2), you have encountered the biggest obstacle of this project. The `build_lookup_table.py` file only serves to build the skeleton of the lookup table, but you must fill it manually. During the development of the project we did not find any way to automatically associate verbs and preprositions with DBpedia properties. In fact, doing this mapping manually is quite complicated and time consuming.
Once you run the `build_lookup_table.py` script you must perform the association of verbs + prepositions with the properties of the ontology you use.

**Comment by maya-25** [comment]
Okay,```build_lookup_table.py``` is also used for  ```get_best_candidates``` function which is enclosing predicates to RDF term type within domain and range. Right now I am getting warning message ``` "Predicates" does not look like a valid URI, trying to serialize this will break.```. As of now I am passing, RDF.type or owl.Ontology for the predicates. so I am getting output like this:
```
RDF triples: <s,p,o>
For the sentence: Serena Williams Beats Venus Williams to Win Her 7th Australian Open Title

For predicates getting this warning msg:
**Beats to Win does not look like a valid URI, trying to serialize this will break.**

[[rdflib.term.URIRef('http://dbpedia.org/resource/Serena_Williams'),
rdflib.term.URIRef('Beats to Win'),
rdflib.term.URIRef('http://dbpedia.org/resource/Venus_Williams')],
[rdflib.term.URIRef('http://dbpedia.org/resource/Serena_Williams'),
rdflib.term.URIRef('Beats to Win'),
rdflib.term.URIRef('http://dbpedia.org/resource/Wikipedia')],
[rdflib.term.URIRef('http://dbpedia.org/resource/Serena_Williams'),
rdflib.term.URIRef('Beats to Win'),
rdflib.term.URIRef('http://dbpedia.org/resource/2013_Australian_Open')]]
```
and corresponding .ttl file:
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
<http://dbpedia.org/resource/Serena_Williams> owl:Ontology <http://dbpedia.org/resource/2013_Australian_Open>,
<http://dbpedia.org/resource/2014_Australian_Open>,
<http://dbpedia.org/resource/Draw_(chess)>,
<http://dbpedia.org/resource/Injury>,
<http://dbpedia.org/resource/Title>,
<http://dbpedia.org/resource/United_States>,
<http://dbpedia.org/resource/Venus_Williams>,
<http://dbpedia.org/resource/Wikipedia> .
```

I would like to ask if this form is correct for generating embeddings for knowledge graphs. Although I have generated the embeddings by RDF2vec using the above .ttl file. Just want to confirm with you whether it's okay, if I don't want to pass the ontology property URIs for predicates manually.

**Comment by Fcabla** [comment]
In order to convert the text to RDF, all elements of the triplet must have a URL prefix. For example in the case of dbpedia it should be: 'http://dbpedia.org/resource/x1' 'http://dbpedia.org/ontology/x2' 'http://dbpedia.org/resource/x3' , where x1 and x3 are resources and x2 is a property. You can also consider that x3 is a literal, for example x1= Serena Williams x2=age x3=40. In this case x3 is not a resource.
In the above example you are treating 'Beats to Win' as a property, which is wrong. This is why it is necessary to manually complete the lookup table.

I guess there shouldn't be any problem to generate embeddings but you would need a knowledge graph with enough entities and links.

**Comment by maya-25** [comment]
Okay, Thanks a lot? 
Is it possible to get the generated RDF triples with URIs for my dataset and with that, I can find the all subgraphs (connecting the relationship between subject and object to check in what sense the entities are related) by traversing the large DBpedia knowledge graph?

**Comment by Fcabla** [comment]
Correct me if I am wrong but I believe that your question is if you can extract the property that relates two entities of the ontology. In that case I guess you can try but there is no guarantee that you will find such a relation, since it may not exist in DBpedia. One of the purposes of the project is to extract RDF triples from the plain text to complete the knowledge graph.

**Comment by maya-25** [comment]
Thanks, I will definitely try to do that. But as of now, my RDF triples are only generated for 6000 titles out of 14000 titles in my dataset. Some of the sentences are skipped and RDF triples are not generated for them. And the embeddings are also generated by RDF2vec for 6000 titles with dimensions (6000,384),  384 vector sizes. But my raw text embeddings are (14000,384). Now I want to concatenate these embeddings(text+KG embeddings) to feed to Multilayer perception. Is it possible to concatenate these embeddings with different dimensions? I know this is out of context question from this Github project. But it would be really helpful if you could give me some idea? I am not able to do it.

**Comment by maya-25** [comment]
I would like to ask, most of the sentences in my dataset are skipped by RDFlib to generate RDF triples (with URIs). For example, I have 20000 sentences so RDF triples are generated only for 6000-7000 sentences. could you please why it is so? Are you able to generate RDF triples for each and every abstract?

**Comment by Fcabla** [comment]
Not every sentence is processed. I maded a distinction between complex (more than 1 verb) and simple sentences (just 1 verb). There are other cases that are not considered. Please recheck the documentation (blog) and the source code to understand the tool and rewrite it to fullfill your needs.
